version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Info@123
      POSTGRES_DB: ead-authuser-v2
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
