server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ricardo-Tonietti/ead-config-server-repo
          default-label: master
          username: ricardo-tonietti
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'

  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


